window.Age5NaturalAudioVersion = "20260812-pronunciation-fix";
window.Age5NaturalAudio = {
  "zh": {
    "先來暖身，慢慢玩。": "audio/natural/zh/age5-zh-001.mp3",
    "厲害！接下來每題有兩件事要注意。": "audio/natural/zh/age5-zh-002.mp3",
    "最後的城市任務：要記住順序、一步一步完成！": "audio/natural/zh/age5-zh-003.mp3",
    "再看一次，慢慢試。": "audio/natural/zh/age5-zh-004.mp3",
    "答對了。": "audio/natural/zh/age5-zh-005.mp3",
    "好棒。": "audio/natural/zh/age5-zh-006.mp3",
    "你做到了。": "audio/natural/zh/age5-zh-007.mp3",
    "遊戲完成了！": "audio/natural/zh/age5-zh-008.mp3",
    "哪個身體部位幫助我們聽聲音？": "audio/natural/zh/age5-zh-009.mp3",
    "聲音進入耳朵。": "audio/natural/zh/age5-zh-010.mp3",
    "聞到麵包香味時，我們用了哪個部位？": "audio/natural/zh/age5-zh-011.mp3",
    "香味的線索會進入鼻子。": "audio/natural/zh/age5-zh-012.mp3",
    "看月亮時，我們主要使用哪個部位？": "audio/natural/zh/age5-zh-013.mp3",
    "光進入眼睛，讓我們看見。": "audio/natural/zh/age5-zh-014.mp3",
    "嚐草莓的味道時，我們使用哪個部位？": "audio/natural/zh/age5-zh-015.mp3",
    "味道會被舌頭感覺到。": "audio/natural/zh/age5-zh-016.mp3",
    "摸到柔軟玩具時，我們主要使用什麼？": "audio/natural/zh/age5-zh-017.mp3",
    "皮膚可以感覺柔軟、粗糙、冷和熱。": "audio/natural/zh/age5-zh-018.mp3",
    "哪個感官能幫你找到正在播放音樂的喇叭？": "audio/natural/zh/age5-zh-019.mp3",
    "跟著聲音走，要使用聽覺。": "audio/natural/zh/age5-zh-020.mp3",
    "哪一個可能會辨認你的臉？": "audio/natural/zh/age5-zh-021.mp3",
    "想想哪個東西會接收資訊，再做出反應。": "audio/natural/zh/age5-zh-022.mp3",
    "哪一個是人製造、會照指令做事的機器？": "audio/natural/zh/age5-zh-023.mp3",
    "哪一個可以聽到問題，再回答你？": "audio/natural/zh/age5-zh-024.mp3",
    "哪一個可能感覺有人靠近，然後自動打開？": "audio/natural/zh/age5-zh-025.mp3",
    "AI 猜錯時，哪一個做法最好？": "audio/natural/zh/age5-zh-026.mp3",
    "哪一個不是有感情的人，而是人做出的工具？": "audio/natural/zh/age5-zh-027.mp3",
    "哪個孩子看起來很開心？": "audio/natural/zh/age5-zh-028.mp3",
    "仔細聽線索，再看看每一張圖。": "audio/natural/zh/age5-zh-029.mp3",
    "哪個孩子看起來需要安慰？": "audio/natural/zh/age5-zh-030.mp3",
    "哪個孩子眉頭皺起、看起來生氣？": "audio/natural/zh/age5-zh-031.mp3",
    "哪個孩子看起來有點害怕？": "audio/natural/zh/age5-zh-032.mp3",
    "找到嘴角上揚的表情。": "audio/natural/zh/age5-zh-033.mp3",
    "找到可以先停下來深呼吸的孩子。": "audio/natural/zh/age5-zh-034.mp3",
    "哪一個方法能幫助身體慢慢安靜？": "audio/natural/zh/age5-zh-035.mp3",
    "哪一個是溫柔的安慰方法？": "audio/natural/zh/age5-zh-036.mp3",
    "活動後，哪個方法能照顧身體？": "audio/natural/zh/age5-zh-037.mp3",
    "生氣時，哪一個不是安全的冷靜方法？": "audio/natural/zh/age5-zh-038.mp3",
    "跟著羽毛慢慢吸氣、吐氣，要選哪張圖？": "audio/natural/zh/age5-zh-039.mp3",
    "口渴又煩躁時可以先做什麼？": "audio/natural/zh/age5-zh-040.mp3",
    "哪張圖表示一起分享？": "audio/natural/zh/age5-zh-041.mp3",
    "朋友還在玩時，可以怎麼做？": "audio/natural/zh/age5-zh-042.mp3",
    "哪個做法可能讓朋友不舒服？": "audio/natural/zh/age5-zh-043.mp3",
    "什麼工具可以幫大家公平輪流？": "audio/natural/zh/age5-zh-044.mp3",
    "兩個人一起使用積木是哪張圖？": "audio/natural/zh/age5-zh-045.mp3",
    "想玩同一個玩具時，先選哪個安全方法？": "audio/natural/zh/age5-zh-046.mp3",
    "拼圖很難時，可以先做什麼？": "audio/natural/zh/age5-zh-047.mp3",
    "試過幾次還是不懂，可以怎麼做？": "audio/natural/zh/age5-zh-048.mp3",
    "身體很累時，哪個選擇有幫助？": "audio/natural/zh/age5-zh-049.mp3",
    "哪個做法不會幫助我們學會？": "audio/natural/zh/age5-zh-050.mp3",
    "找到『換個方法再試一次』的圖。": "audio/natural/zh/age5-zh-051.mp3",
    "短暫休息後，我們可以再回來。是哪張圖？": "audio/natural/zh/age5-zh-052.mp3",
    "植物生長需要哪一樣？": "audio/natural/zh/age5-zh-053.mp3",
    "植物的葉子需要哪一種光？": "audio/natural/zh/age5-zh-054.mp3",
    "動物需要什麼來獲得能量？": "audio/natural/zh/age5-zh-055.mp3",
    "哪一樣不是所有生物生存的基本需要？": "audio/natural/zh/age5-zh-056.mp3",
    "口渴的動物需要什麼？": "audio/natural/zh/age5-zh-057.mp3",
    "找到能溫暖並照亮植物的東西。": "audio/natural/zh/age5-zh-058.mp3",
    "騎滑步車前要戴什麼？": "audio/natural/zh/age5-zh-059.mp3",
    "過馬路時，哪張圖最安全？": "audio/natural/zh/age5-zh-060.mp3",
    "看到不認識的藥，應該請大人處理哪一個？": "audio/natural/zh/age5-zh-061.mp3",
    "手指不可以碰哪裡？": "audio/natural/zh/age5-zh-062.mp3",
    "找到保護頭部的東西。": "audio/natural/zh/age5-zh-063.mp3",
    "要過馬路時，先找誰幫忙？": "audio/natural/zh/age5-zh-064.mp3",
    "執行任務前，機器人要先在哪裡？": "audio/natural/zh/age5-zh-065.mp3",
    "指令『向前一步』是哪張圖？": "audio/natural/zh/age5-zh-066.mp3",
    "道路彎了，需要哪個指令？": "audio/natural/zh/age5-zh-067.mp3",
    "完成所有指令後，機器人會到哪裡？": "audio/natural/zh/age5-zh-068.mp3",
    "找到第一步開始的位置。": "audio/natural/zh/age5-zh-069.mp3",
    "找到任務完成的畫面。": "audio/natural/zh/age5-zh-070.mp3",
    "科學家用什麼知道恐龍曾經存在？": "audio/natural/zh/age5-zh-071.mp3",
    "哪隻恐龍有很大的牙齒和兩隻短前臂？": "audio/natural/zh/age5-zh-072.mp3",
    "哪隻恐龍有三根角和大頭盾？": "audio/natural/zh/age5-zh-073.mp3",
    "哪張圖不符合真實歷史？": "audio/natural/zh/age5-zh-074.mp3",
    "找到保存在岩石裡的恐龍線索。": "audio/natural/zh/age5-zh-075.mp3",
    "找到吃植物的三角龍。": "audio/natural/zh/age5-zh-076.mp3",
    "哪一種昆蟲有彩色翅膀？": "audio/natural/zh/age5-zh-077.mp3",
    "哪一種昆蟲常和同伴一起搬食物？": "audio/natural/zh/age5-zh-078.mp3",
    "哪一種小生物有八隻腳，不是昆蟲？": "audio/natural/zh/age5-zh-079.mp3",
    "哪一種小生物背著殼慢慢爬？": "audio/natural/zh/age5-zh-080.mp3",
    "找到有六隻腳的小螞蟻。": "audio/natural/zh/age5-zh-081.mp3",
    "找到會織網的動物。": "audio/natural/zh/age5-zh-082.mp3",
    "哪一種大型海洋動物要到水面呼吸？": "audio/natural/zh/age5-zh-083.mp3",
    "哪一種動物有八隻腕足？": "audio/natural/zh/age5-zh-084.mp3",
    "哪一種爬行動物有硬殼和鰭狀肢？": "audio/natural/zh/age5-zh-085.mp3",
    "哪張圖表示許多魚一起游？": "audio/natural/zh/age5-zh-086.mp3",
    "找到會噴氣的鯨魚。": "audio/natural/zh/age5-zh-087.mp3",
    "找到能用腕足抓住東西的動物。": "audio/natural/zh/age5-zh-088.mp3",
    "哪個器官不停把血送到全身？": "audio/natural/zh/age5-zh-089.mp3",
    "呼吸時，空氣進入哪裡？": "audio/natural/zh/age5-zh-090.mp3",
    "吃下食物後，哪個器官幫忙消化？": "audio/natural/zh/age5-zh-091.mp3",
    "什麼支撐身體並保護器官？": "audio/natural/zh/age5-zh-092.mp3",
    "跑跳後會跳得更快的是哪一個？": "audio/natural/zh/age5-zh-093.mp3",
    "深深吸氣時，哪一個會充滿空氣？": "audio/natural/zh/age5-zh-094.mp3",
    "天空明亮、幾乎沒有雲，是什麼天氣？": "audio/natural/zh/age5-zh-095.mp3",
    "需要雨傘的是什麼天氣？": "audio/natural/zh/age5-zh-096.mp3",
    "樹葉一直飛舞，是什麼天氣？": "audio/natural/zh/age5-zh-097.mp3",
    "看到閃電、聽到雷聲，是什麼天氣？": "audio/natural/zh/age5-zh-098.mp3",
    "找到可以穿雨鞋踩水窪的天氣。": "audio/natural/zh/age5-zh-099.mp3",
    "找到風箏容易飛起來的天氣。": "audio/natural/zh/age5-zh-100.mp3",
    "花朵常在什麼季節大量開放？": "audio/natural/zh/age5-zh-101.mp3",
    "哪個季節通常最炎熱？": "audio/natural/zh/age5-zh-102.mp3",
    "許多樹葉變色落下，是什麼季節？": "audio/natural/zh/age5-zh-103.mp3",
    "有些地方會在什麼季節下雪？": "audio/natural/zh/age5-zh-104.mp3",
    "找到春天的新花朵。": "audio/natural/zh/age5-zh-105.mp3",
    "找到需要厚外套的季節。": "audio/natural/zh/age5-zh-106.mp3",
    "哪一顆星照亮並溫暖地球？": "audio/natural/zh/age5-zh-107.mp3",
    "夜晚常看到哪個天體繞著地球運行？": "audio/natural/zh/age5-zh-108.mp3",
    "我們住在哪顆行星？": "audio/natural/zh/age5-zh-109.mp3",
    "誰穿著太空衣到太空工作？": "audio/natural/zh/age5-zh-110.mp3",
    "找到有海洋和陸地的藍色行星。": "audio/natural/zh/age5-zh-111.mp3",
    "找到會反射太陽光的月亮。": "audio/natural/zh/age5-zh-112.mp3",
    "哪一座山可能噴出熔岩和灰？": "audio/natural/zh/age5-zh-113.mp3",
    "地面突然搖動叫做什麼？": "audio/natural/zh/age5-zh-114.mp3",
    "地震時，哪個動作能保護自己？": "audio/natural/zh/age5-zh-115.mp3",
    "火山噴出、非常熱的融化岩石叫什麼？": "audio/natural/zh/age5-zh-116.mp3",
    "找到『趴下、掩護、穩住』的安全動作。": "audio/natural/zh/age5-zh-117.mp3",
    "找到正在噴發的火山。": "audio/natural/zh/age5-zh-118.mp3",
    "身體每天都需要哪一樣？": "audio/natural/zh/age5-zh-119.mp3",
    "哪一樣能提供安全的居住空間？": "audio/natural/zh/age5-zh-120.mp3",
    "哪一樣很好玩，但不是生存必需品？": "audio/natural/zh/age5-zh-121.mp3",
    "哪一樣是偶爾想吃的點心？": "audio/natural/zh/age5-zh-122.mp3",
    "口渴時，先選需要的東西。": "audio/natural/zh/age5-zh-123.mp3",
    "找到一個『想要』而不是『需要』的物品。": "audio/natural/zh/age5-zh-124.mp3",
    "買東西的第一步可以是什麼？": "audio/natural/zh/age5-zh-125.mp3",
    "選好商品後，要做什麼？": "audio/natural/zh/age5-zh-126.mp3",
    "哪一張紙可以記錄買了什麼？": "audio/natural/zh/age5-zh-127.mp3",
    "哪個做法不可以？": "audio/natural/zh/age5-zh-128.mp3",
    "找到把錢交給店員的畫面。": "audio/natural/zh/age5-zh-129.mp3",
    "找到購物後可能拿到的小紙張。": "audio/natural/zh/age5-zh-130.mp3",
    "哪一個容器可以收好要存的錢？": "audio/natural/zh/age5-zh-131.mp3",
    "每次存一點，可以先放進什麼？": "audio/natural/zh/age5-zh-132.mp3",
    "哪張圖表示一個儲蓄目標？": "audio/natural/zh/age5-zh-133.mp3",
    "哪個選擇會讓存款變少？": "audio/natural/zh/age5-zh-134.mp3",
    "找到可以看見硬幣慢慢增加的容器。": "audio/natural/zh/age5-zh-135.mp3",
    "想存錢時，先想清楚要達成什麼。是哪張圖？": "audio/natural/zh/age5-zh-136.mp3",
    "哪一種機器人可以在工廠重複搬東西？": "audio/natural/zh/age5-zh-137.mp3",
    "哪一種機器人會在地板上移動清潔？": "audio/natural/zh/age5-zh-138.mp3",
    "哪一種機器人能探索遙遠的行星？": "audio/natural/zh/age5-zh-139.mp3",
    "哪一個不是機器人？": "audio/natural/zh/age5-zh-140.mp3",
    "找到有輪子、能探索岩石的機器人。": "audio/natural/zh/age5-zh-141.mp3",
    "找到能在家裡幫忙清潔的機器。": "audio/natural/zh/age5-zh-142.mp3",
    "哪個裝置可以接收許多資訊並執行應用程式？": "audio/natural/zh/age5-zh-143.mp3",
    "哪個裝置能聽語音指令並回答？": "audio/natural/zh/age5-zh-144.mp3",
    "哪個裝置只要按開關就亮，不一定很智慧？": "audio/natural/zh/age5-zh-145.mp3",
    "哪一樣完全不是電子裝置？": "audio/natural/zh/age5-zh-146.mp3",
    "找到可能連上網路的電話。": "audio/natural/zh/age5-zh-147.mp3",
    "找到只能拿來攪拌食物的工具。": "audio/natural/zh/age5-zh-148.mp3",
    "語音助理的第一步是什麼？": "audio/natural/zh/age5-zh-149.mp3",
    "收到聲音後，電腦會找什麼？": "audio/natural/zh/age5-zh-150.mp3",
    "找到可能的意思後，裝置可以做什麼？": "audio/natural/zh/age5-zh-151.mp3",
    "使用語音助理時，哪個做法很重要？": "audio/natural/zh/age5-zh-152.mp3",
    "找到把聲音變成電腦線索的第一步。": "audio/natural/zh/age5-zh-153.mp3",
    "找到裝置把結果說出來的畫面。": "audio/natural/zh/age5-zh-154.mp3",
    "哪一座古代建築有寬底和尖頂？": "audio/natural/zh/age5-zh-155.mp3",
    "金字塔主要用什麼堆疊建造？": "audio/natural/zh/age5-zh-156.mp3",
    "哪條河流經古埃及並幫助運送物資？": "audio/natural/zh/age5-zh-157.mp3",
    "古埃及工人沒有哪一種現代機器？": "audio/natural/zh/age5-zh-158.mp3",
    "找到故事中的大型石造陵墓。": "audio/natural/zh/age5-zh-159.mp3",
    "找到可能用船運送石材的河流。": "audio/natural/zh/age5-zh-160.mp3",
    "哪個高高的地方可以向遠處觀察？": "audio/natural/zh/age5-zh-161.mp3",
    "哪個入口可以升起來保護城堡？": "audio/natural/zh/age5-zh-162.mp3",
    "大家可能在哪裡一起吃飯和開會？": "audio/natural/zh/age5-zh-163.mp3",
    "古代城堡裡通常沒有什麼？": "audio/natural/zh/age5-zh-164.mp3",
    "找到城堡的高塔。": "audio/natural/zh/age5-zh-165.mp3",
    "找到可以讓人進出城堡的大門。": "audio/natural/zh/age5-zh-166.mp3",
    "騎士穿什麼保護身體？": "audio/natural/zh/age5-zh-167.mp3",
    "騎士手上拿什麼擋住攻擊？": "audio/natural/zh/age5-zh-168.mp3",
    "騎士常騎什麼動物旅行？": "audio/natural/zh/age5-zh-169.mp3",
    "哪一樣不屬於騎士故事？": "audio/natural/zh/age5-zh-170.mp3",
    "找到金屬製的保護衣。": "audio/natural/zh/age5-zh-171.mp3",
    "找到有徽章圖案的防護板。": "audio/natural/zh/age5-zh-172.mp3",
    "故事裡哪位女神常和智慧的貓頭鷹一起出現？": "audio/natural/zh/age5-zh-173.mp3",
    "哪位海神拿著三叉戟？": "audio/natural/zh/age5-zh-174.mp3",
    "哪一匹神話中的馬有翅膀？": "audio/natural/zh/age5-zh-175.mp3",
    "哪個角色不屬於古希臘神話？": "audio/natural/zh/age5-zh-176.mp3",
    "找到故事中的飛馬。": "audio/natural/zh/age5-zh-177.mp3",
    "找到掌管海洋的神話人物。": "audio/natural/zh/age5-zh-178.mp3",
    "觀察顏色和形狀時會用什麼？": "audio/natural/zh/age5-zh-179.mp3",
    "哪個工具能讓小細節看起來更大？": "audio/natural/zh/age5-zh-180.mp3",
    "想知道樹皮粗不粗，可以怎麼觀察？": "audio/natural/zh/age5-zh-181.mp3",
    "哪一個不是仔細觀察？": "audio/natural/zh/age5-zh-182.mp3",
    "找到能看見葉脈細節的工具。": "audio/natural/zh/age5-zh-183.mp3",
    "找到用觸覺蒐集線索的方法。": "audio/natural/zh/age5-zh-184.mp3",
    "看到冰融化，可以從哪張圖開始問『為什麼』？": "audio/natural/zh/age5-zh-185.mp3",
    "哪張圖可以問『如果光線不同會怎樣』？": "audio/natural/zh/age5-zh-186.mp3",
    "不懂時，可以做什麼？": "audio/natural/zh/age5-zh-187.mp3",
    "科學問題開始時，不應該立刻做什麼？": "audio/natural/zh/age5-zh-188.mp3",
    "找到一個可以比較兩種情況的問題。": "audio/natural/zh/age5-zh-189.mp3",
    "找到勇敢說出問題的孩子。": "audio/natural/zh/age5-zh-190.mp3",
    "公平比較時，可以先準備什麼？": "audio/natural/zh/age5-zh-191.mp3",
    "浮沉實驗的下一步可以做什麼？": "audio/natural/zh/age5-zh-192.mp3",
    "物品進水後，要仔細做什麼？": "audio/natural/zh/age5-zh-193.mp3",
    "實驗材料不可以隨便怎麼做？": "audio/natural/zh/age5-zh-194.mp3",
    "找到比較結果的觀察畫面。": "audio/natural/zh/age5-zh-195.mp3",
    "找到把物品輕輕放入水中的步驟。": "audio/natural/zh/age5-zh-196.mp3",
    "實驗開始前，可以先畫什麼？": "audio/natural/zh/age5-zh-197.mp3",
    "種子發芽後，要新增哪一張記錄？": "audio/natural/zh/age5-zh-198.mp3",
    "要記錄看見五個，可以用什麼？": "audio/natural/zh/age5-zh-199.mp3",
    "哪個做法會讓觀察記錄消失？": "audio/natural/zh/age5-zh-200.mp3",
    "找到能比較變化之後的圖。": "audio/natural/zh/age5-zh-201.mp3",
    "找到不用寫很多字也能記數量的方法。": "audio/natural/zh/age5-zh-202.mp3",
    "科學任務可以從哪一步開始？": "audio/natural/zh/age5-zh-203.mp3",
    "觀察後，下一步可以做什麼？": "audio/natural/zh/age5-zh-204.mp3",
    "要尋找答案，可以安全地做什麼？": "audio/natural/zh/age5-zh-205.mp3",
    "做完測試後，要怎麼保存結果？": "audio/natural/zh/age5-zh-206.mp3",
    "找到用眼睛蒐集線索的步驟。": "audio/natural/zh/age5-zh-207.mp3",
    "找到最後把看到的結果畫下來的步驟。": "audio/natural/zh/age5-zh-208.mp3",
    "找出三對海洋動物。": "audio/natural/zh/age5-zh-209.mp3",
    "翻開兩張圖，記住它們的位置。": "audio/natural/zh/age5-zh-210.mp3",
    "找出三對恐龍朋友。": "audio/natural/zh/age5-zh-211.mp3",
    "找出四對小小朋友。": "audio/natural/zh/age5-zh-212.mp3",
    "找出四對天空圖卡。": "audio/natural/zh/age5-zh-213.mp3",
    "找出五對太空朋友。": "audio/natural/zh/age5-zh-214.mp3",
    "完成六對綜合記憶挑戰。": "audio/natural/zh/age5-zh-215.mp3",
    "記住蘋果、香蕉和草莓。": "audio/natural/zh/age5-zh-216.mp3",
    "慢慢看每一張圖。": "audio/natural/zh/age5-zh-217.mp3",
    "哪一個不見了？": "audio/natural/zh/age5-zh-218.mp3",
    "看看留下來的圖片，再想想剛才還看見了誰。": "audio/natural/zh/age5-zh-219.mp3",
    "記住暴龍、三角龍和恐龍蛋。": "audio/natural/zh/age5-zh-220.mp3",
    "記住四個小生物。": "audio/natural/zh/age5-zh-221.mp3",
    "記住太陽、月亮、地球和火箭。": "audio/natural/zh/age5-zh-222.mp3",
    "記住眼睛、耳朵、鼻子、舌頭和雙手。": "audio/natural/zh/age5-zh-223.mp3",
    "記住這五張綜合圖卡。": "audio/natural/zh/age5-zh-224.mp3",
    "小耳朵準備好了。仔細聽，哪張圖是聲音的朋友？": "audio/natural/zh/age5-zh-225.mp3",
    "按一下再聽一次，找出聲音的來源。": "audio/natural/zh/age5-zh-226.mp3",
    "先是月亮，然後是火箭。仔細記住。": "audio/natural/zh/age5-zh-227.mp3",
    "看圖片一張一張亮起來。": "audio/natural/zh/age5-zh-228.mp3",
    "現在換你，照剛才的順序點圖片。": "audio/natural/zh/age5-zh-229.mp3",
    "想想第一張亮起來的是什麼。": "audio/natural/zh/age5-zh-230.mp3",
    "先是蝴蝶，然後是花朵。仔細記住。": "audio/natural/zh/age5-zh-231.mp3",
    "恐龍蛋、三角龍、化石。記住這個順序。": "audio/natural/zh/age5-zh-232.mp3",
    "麥克風、電腦、智慧音箱。記住語音助理的順序。": "audio/natural/zh/age5-zh-233.mp3",
    "觀察、提問、實驗、畫圖。記住科學任務。": "audio/natural/zh/age5-zh-234.mp3",
    "太陽、地球、月亮、太空人。完成最後的太空順序。": "audio/natural/zh/age5-zh-235.mp3",
    "耳朵": "audio/natural/zh/age5-zh-236.mp3",
    "眼睛": "audio/natural/zh/age5-zh-237.mp3",
    "鼻子": "audio/natural/zh/age5-zh-238.mp3",
    "舌頭": "audio/natural/zh/age5-zh-239.mp3",
    "皮膚和手": "audio/natural/zh/age5-zh-240.mp3",
    "聽覺": "audio/natural/zh/age5-zh-241.mp3",
    "嗅覺": "audio/natural/zh/age5-zh-242.mp3",
    "味覺": "audio/natural/zh/age5-zh-243.mp3",
    "手機": "audio/natural/zh/age5-zh-244.mp3",
    "湯匙": "audio/natural/zh/age5-zh-245.mp3",
    "紙本書": "audio/natural/zh/age5-zh-246.mp3",
    "機器人": "audio/natural/zh/age5-zh-247.mp3",
    "小狗": "audio/natural/zh/age5-zh-248.mp3",
    "大人": "audio/natural/zh/age5-zh-249.mp3",
    "智慧喇叭": "audio/natural/zh/age5-zh-250.mp3",
    "碗": "audio/natural/zh/age5-zh-251.mp3",
    "毛巾": "audio/natural/zh/age5-zh-252.mp3",
    "自動門": "audio/natural/zh/age5-zh-253.mp3",
    "香蕉": "audio/natural/zh/age5-zh-254.mp3",
    "書": "audio/natural/zh/age5-zh-255.mp3",
    "告訴大人並再確認": "audio/natural/zh/age5-zh-256.mp3",
    "永遠相信機器": "audio/natural/zh/age5-zh-257.mp3",
    "假裝沒看見": "audio/natural/zh/age5-zh-258.mp3",
    "AI 機器人": "audio/natural/zh/age5-zh-259.mp3",
    "小朋友": "audio/natural/zh/age5-zh-260.mp3",
    "開心的孩子": "audio/natural/zh/age5-zh-261.mp3",
    "難過的孩子": "audio/natural/zh/age5-zh-262.mp3",
    "生氣的孩子": "audio/natural/zh/age5-zh-263.mp3",
    "害怕的孩子": "audio/natural/zh/age5-zh-264.mp3",
    "吹羽毛慢慢呼吸": "audio/natural/zh/age5-zh-265.mp3",
    "抱抱玩偶": "audio/natural/zh/age5-zh-266.mp3",
    "喝水": "audio/natural/zh/age5-zh-267.mp3",
    "大聲吼叫": "audio/natural/zh/age5-zh-268.mp3",
    "兩個孩子分享積木": "audio/natural/zh/age5-zh-269.mp3",
    "孩子等待輪流": "audio/natural/zh/age5-zh-270.mp3",
    "搶走玩具": "audio/natural/zh/age5-zh-271.mp3",
    "沙漏計時輪流": "audio/natural/zh/age5-zh-272.mp3",
    "孩子再試一次拼圖": "audio/natural/zh/age5-zh-273.mp3",
    "向大人求助": "audio/natural/zh/age5-zh-274.mp3",
    "休息一下": "audio/natural/zh/age5-zh-275.mp3",
    "把拼圖丟開": "audio/natural/zh/age5-zh-276.mp3",
    "水": "audio/natural/zh/age5-zh-277.mp3",
    "陽光": "audio/natural/zh/age5-zh-278.mp3",
    "食物": "audio/natural/zh/age5-zh-279.mp3",
    "玩具車": "audio/natural/zh/age5-zh-280.mp3",
    "戴安全帽的孩子": "audio/natural/zh/age5-zh-281.mp3",
    "牽著大人過馬路": "audio/natural/zh/age5-zh-282.mp3",
    "藥瓶": "audio/natural/zh/age5-zh-283.mp3",
    "插座": "audio/natural/zh/age5-zh-284.mp3",
    "機器人站在起點": "audio/natural/zh/age5-zh-285.mp3",
    "機器人向前走": "audio/natural/zh/age5-zh-286.mp3",
    "機器人轉彎": "audio/natural/zh/age5-zh-287.mp3",
    "機器人到達星星": "audio/natural/zh/age5-zh-288.mp3",
    "恐龍化石": "audio/natural/zh/age5-zh-289.mp3",
    "暴龍": "audio/natural/zh/age5-zh-290.mp3",
    "三角龍": "audio/natural/zh/age5-zh-291.mp3",
    "現代人與恐龍並肩": "audio/natural/zh/age5-zh-292.mp3",
    "蝴蝶": "audio/natural/zh/age5-zh-293.mp3",
    "螞蟻": "audio/natural/zh/age5-zh-294.mp3",
    "蜘蛛": "audio/natural/zh/age5-zh-295.mp3",
    "蝸牛": "audio/natural/zh/age5-zh-296.mp3",
    "鯨魚": "audio/natural/zh/age5-zh-297.mp3",
    "章魚": "audio/natural/zh/age5-zh-298.mp3",
    "海龜": "audio/natural/zh/age5-zh-299.mp3",
    "魚群": "audio/natural/zh/age5-zh-300.mp3",
    "心臟": "audio/natural/zh/age5-zh-301.mp3",
    "肺": "audio/natural/zh/age5-zh-302.mp3",
    "胃": "audio/natural/zh/age5-zh-303.mp3",
    "骨骼": "audio/natural/zh/age5-zh-304.mp3",
    "晴天": "audio/natural/zh/age5-zh-305.mp3",
    "雨天": "audio/natural/zh/age5-zh-306.mp3",
    "颳風": "audio/natural/zh/age5-zh-307.mp3",
    "雷雨": "audio/natural/zh/age5-zh-308.mp3",
    "春天花朵": "audio/natural/zh/age5-zh-309.mp3",
    "夏天陽光": "audio/natural/zh/age5-zh-310.mp3",
    "秋天落葉": "audio/natural/zh/age5-zh-311.mp3",
    "冬天雪景": "audio/natural/zh/age5-zh-312.mp3",
    "太陽": "audio/natural/zh/age5-zh-313.mp3",
    "月亮": "audio/natural/zh/age5-zh-314.mp3",
    "地球": "audio/natural/zh/age5-zh-315.mp3",
    "太空人": "audio/natural/zh/age5-zh-316.mp3",
    "噴發的火山": "audio/natural/zh/age5-zh-317.mp3",
    "搖動的地面": "audio/natural/zh/age5-zh-318.mp3",
    "趴下掩護穩住": "audio/natural/zh/age5-zh-319.mp3",
    "熔岩": "audio/natural/zh/age5-zh-320.mp3",
    "飲用水": "audio/natural/zh/age5-zh-321.mp3",
    "住家": "audio/natural/zh/age5-zh-322.mp3",
    "新玩具": "audio/natural/zh/age5-zh-323.mp3",
    "糖果": "audio/natural/zh/age5-zh-324.mp3",
    "選一顆蘋果": "audio/natural/zh/age5-zh-325.mp3",
    "付錢": "audio/natural/zh/age5-zh-326.mp3",
    "收據": "audio/natural/zh/age5-zh-327.mp3",
    "沒付錢就帶走": "audio/natural/zh/age5-zh-328.mp3",
    "存錢罐": "audio/natural/zh/age5-zh-329.mp3",
    "一枚硬幣": "audio/natural/zh/age5-zh-330.mp3",
    "想買的腳踏車": "audio/natural/zh/age5-zh-331.mp3",
    "立刻買糖果": "audio/natural/zh/age5-zh-332.mp3",
    "工廠機器手臂": "audio/natural/zh/age5-zh-333.mp3",
    "掃地機器人": "audio/natural/zh/age5-zh-334.mp3",
    "火星探測車": "audio/natural/zh/age5-zh-335.mp3",
    "真人朋友": "audio/natural/zh/age5-zh-336.mp3",
    "智慧手機": "audio/natural/zh/age5-zh-337.mp3",
    "智慧音箱": "audio/natural/zh/age5-zh-338.mp3",
    "普通檯燈": "audio/natural/zh/age5-zh-339.mp3",
    "木湯匙": "audio/natural/zh/age5-zh-340.mp3",
    "麥克風接收聲音": "audio/natural/zh/age5-zh-341.mp3",
    "電腦比對語音模式": "audio/natural/zh/age5-zh-342.mp3",
    "音箱說出回答": "audio/natural/zh/age5-zh-343.mp3",
    "不分享私人資料": "audio/natural/zh/age5-zh-344.mp3",
    "埃及金字塔": "audio/natural/zh/age5-zh-345.mp3",
    "巨大石塊": "audio/natural/zh/age5-zh-346.mp3",
    "尼羅河與船": "audio/natural/zh/age5-zh-347.mp3",
    "現代起重機": "audio/natural/zh/age5-zh-348.mp3",
    "高塔": "audio/natural/zh/age5-zh-349.mp3",
    "吊橋與城門": "audio/natural/zh/age5-zh-350.mp3",
    "城堡大廳": "audio/natural/zh/age5-zh-351.mp3",
    "現代車庫": "audio/natural/zh/age5-zh-352.mp3",
    "騎士盔甲": "audio/natural/zh/age5-zh-353.mp3",
    "盾牌": "audio/natural/zh/age5-zh-354.mp3",
    "馬": "audio/natural/zh/age5-zh-355.mp3",
    "太空衣": "audio/natural/zh/age5-zh-356.mp3",
    "雅典娜與貓頭鷹": "audio/natural/zh/age5-zh-357.mp3",
    "波塞頓與三叉戟": "audio/natural/zh/age5-zh-358.mp3",
    "飛馬佩加索斯": "audio/natural/zh/age5-zh-359.mp3",
    "現代機器人": "audio/natural/zh/age5-zh-360.mp3",
    "孩子用眼睛看葉子": "audio/natural/zh/age5-zh-361.mp3",
    "放大鏡": "audio/natural/zh/age5-zh-362.mp3",
    "手摸樹皮": "audio/natural/zh/age5-zh-363.mp3",
    "閉眼亂猜": "audio/natural/zh/age5-zh-364.mp3",
    "孩子觀察融化的冰": "audio/natural/zh/age5-zh-365.mp3",
    "兩株植物不同光線": "audio/natural/zh/age5-zh-366.mp3",
    "舉手提問": "audio/natural/zh/age5-zh-367.mp3",
    "直接宣布答案": "audio/natural/zh/age5-zh-368.mp3",
    "兩杯水": "audio/natural/zh/age5-zh-369.mp3",
    "把物品放入水中": "audio/natural/zh/age5-zh-370.mp3",
    "觀察浮或沉": "audio/natural/zh/age5-zh-371.mp3",
    "品嚐實驗材料": "audio/natural/zh/age5-zh-372.mp3",
    "實驗前的種子圖": "audio/natural/zh/age5-zh-373.mp3",
    "發芽後的圖": "audio/natural/zh/age5-zh-374.mp3",
    "計數記號": "audio/natural/zh/age5-zh-375.mp3",
    "把結果全部擦掉": "audio/natural/zh/age5-zh-376.mp3",
    "觀察葉子": "audio/natural/zh/age5-zh-377.mp3",
    "提出問題": "audio/natural/zh/age5-zh-378.mp3",
    "做簡單測試": "audio/natural/zh/age5-zh-379.mp3",
    "畫圖記錄": "audio/natural/zh/age5-zh-380.mp3",
    "恐龍蛋": "audio/natural/zh/age5-zh-381.mp3",
    "蜜蜂": "audio/natural/zh/age5-zh-382.mp3",
    "雨雲": "audio/natural/zh/age5-zh-383.mp3",
    "風": "audio/natural/zh/age5-zh-384.mp3",
    "火箭": "audio/natural/zh/age5-zh-385.mp3",
    "蘋果": "audio/natural/zh/age5-zh-386.mp3",
    "草莓": "audio/natural/zh/age5-zh-387.mp3",
    "花朵": "audio/natural/zh/age5-zh-388.mp3",
    "雙手": "audio/natural/zh/age5-zh-389.mp3",
    "海洋": "audio/natural/zh/age5-zh-390.mp3",
    "森林": "audio/natural/zh/age5-zh-391.mp3",
    "城堡": "audio/natural/zh/age5-zh-392.mp3",
    "雷雨雲": "audio/natural/zh/age5-zh-393.mp3",
    "船": "audio/natural/zh/age5-zh-394.mp3",
    "腳踏車": "audio/natural/zh/age5-zh-395.mp3",
    "化石": "audio/natural/zh/age5-zh-396.mp3",
    "麥克風": "audio/natural/zh/age5-zh-397.mp3",
    "電腦": "audio/natural/zh/age5-zh-398.mp3",
    "做實驗": "audio/natural/zh/age5-zh-399.mp3"
  },
  "en": {
    "Let's warm up. Nice and easy.": "audio/natural/en/age5-en-001.mp3",
    "Great job! Now watch for two things at once.": "audio/natural/en/age5-en-002.mp3",
    "The big City Mission: remember the steps, one by one!": "audio/natural/en/age5-en-003.mp3",
    "Look again. Take your time.": "audio/natural/en/age5-en-004.mp3",
    "That's right!": "audio/natural/en/age5-en-005.mp3",
    "Great job!": "audio/natural/en/age5-en-006.mp3",
    "You did it!": "audio/natural/en/age5-en-007.mp3",
    "You finished the game!": "audio/natural/en/age5-en-008.mp3",
    "Listen: car. Tap the picture that rhymes with car.": "audio/natural/en/age5-en-009.mp3",
    "Say the ending slowly: car. Which picture ends with the same sound?": "audio/natural/en/age5-en-010.mp3",
    "Listen: cat. Tap the picture that rhymes with cat.": "audio/natural/en/age5-en-011.mp3",
    "Say the ending slowly: cat. Which picture ends with the same sound?": "audio/natural/en/age5-en-012.mp3",
    "Listen: dog. Tap the picture that rhymes with dog.": "audio/natural/en/age5-en-013.mp3",
    "Say the ending slowly: dog. Which picture ends with the same sound?": "audio/natural/en/age5-en-014.mp3",
    "Listen: fish. Tap the picture that rhymes with fish.": "audio/natural/en/age5-en-015.mp3",
    "Say the ending slowly: fish. Which picture ends with the same sound?": "audio/natural/en/age5-en-016.mp3",
    "Listen: moon. Tap the picture that rhymes with moon.": "audio/natural/en/age5-en-017.mp3",
    "Say the ending slowly: moon. Which picture ends with the same sound?": "audio/natural/en/age5-en-018.mp3",
    "Listen: star. Tap the picture that rhymes with star.": "audio/natural/en/age5-en-019.mp3",
    "Say the ending slowly: star. Which picture ends with the same sound?": "audio/natural/en/age5-en-020.mp3",
    "Tap 6. Count out loud as you tap.": "audio/natural/en/age5-en-021.mp3",
    "Start at one. Touch one picture for every number until 6.": "audio/natural/en/age5-en-022.mp3",
    "Tap 9. Count out loud as you tap.": "audio/natural/en/age5-en-023.mp3",
    "Start at one. Touch one picture for every number until 9.": "audio/natural/en/age5-en-024.mp3",
    "Tap 12. Count out loud as you tap.": "audio/natural/en/age5-en-025.mp3",
    "Start at one. Touch one picture for every number until 12.": "audio/natural/en/age5-en-026.mp3",
    "Tap 15. Count out loud as you tap.": "audio/natural/en/age5-en-027.mp3",
    "Start at one. Touch one picture for every number until 15.": "audio/natural/en/age5-en-028.mp3",
    "Tap 18. Count out loud as you tap.": "audio/natural/en/age5-en-029.mp3",
    "Start at one. Touch one picture for every number until 18.": "audio/natural/en/age5-en-030.mp3",
    "Tap 20. Count out loud as you tap.": "audio/natural/en/age5-en-031.mp3",
    "Start at one. Touch one picture for every number until 20.": "audio/natural/en/age5-en-032.mp3",
    "Which body part helps us hear sounds?": "audio/natural/en/age5-en-033.mp3",
    "Sounds go into our ears.": "audio/natural/en/age5-en-034.mp3",
    "Which body part smells fresh bread?": "audio/natural/en/age5-en-035.mp3",
    "Smell clues enter the nose.": "audio/natural/en/age5-en-036.mp3",
    "Which body part do we use to see the Moon?": "audio/natural/en/age5-en-037.mp3",
    "Light enters our eyes so we can see.": "audio/natural/en/age5-en-038.mp3",
    "Which body part tastes a strawberry?": "audio/natural/en/age5-en-039.mp3",
    "The tongue detects flavours.": "audio/natural/en/age5-en-040.mp3",
    "What do we mainly use to feel a soft toy?": "audio/natural/en/age5-en-041.mp3",
    "Skin can feel soft, rough, cold, and hot.": "audio/natural/en/age5-en-042.mp3",
    "Which sense helps you find a speaker playing music?": "audio/natural/en/age5-en-043.mp3",
    "Follow the sound with your hearing.": "audio/natural/en/age5-en-044.mp3",
    "Which one might recognise your face?": "audio/natural/en/age5-en-045.mp3",
    "Which one receives information and then responds?": "audio/natural/en/age5-en-046.mp3",
    "Which one is a human-made machine that follows instructions?": "audio/natural/en/age5-en-047.mp3",
    "Which one can hear a question and answer?": "audio/natural/en/age5-en-048.mp3",
    "Which one may sense a person and open automatically?": "audio/natural/en/age5-en-049.mp3",
    "What should we do when AI makes a wrong guess?": "audio/natural/en/age5-en-050.mp3",
    "Which one is a tool made by people, not a person with feelings?": "audio/natural/en/age5-en-051.mp3",
    "Blend /s/ /u/ /n/. Which picture is sun?": "audio/natural/en/age5-en-052.mp3",
    "Listen to the clue again and look at every picture.": "audio/natural/en/age5-en-053.mp3",
    "Blend /m/ /a/ /p/. Which picture is map?": "audio/natural/en/age5-en-054.mp3",
    "Blend /f/ /i/ /sh/. Which picture is fish?": "audio/natural/en/age5-en-055.mp3",
    "Blend /c/ /u/ /p/. Which picture is cup?": "audio/natural/en/age5-en-056.mp3",
    "Listen: /s/ /u/ /n/. Tap sun.": "audio/natural/en/age5-en-057.mp3",
    "Listen: /f/ /i/ /sh/. Tap fish.": "audio/natural/en/age5-en-058.mp3",
    "Who could be a character in a story?": "audio/natural/en/age5-en-059.mp3",
    "Which picture shows a setting?": "audio/natural/en/age5-en-060.mp3",
    "Which picture shows an event happening?": "audio/natural/en/age5-en-061.mp3",
    "Who is a make-believe character?": "audio/natural/en/age5-en-062.mp3",
    "The story happens among many trees. Find the setting.": "audio/natural/en/age5-en-063.mp3",
    "The friends spread a blanket and eat. Find the event.": "audio/natural/en/age5-en-064.mp3",
    "What comes first when a flower begins to grow?": "audio/natural/en/age5-en-065.mp3",
    "What grows after the seed?": "audio/natural/en/age5-en-066.mp3",
    "What may we see at the end?": "audio/natural/en/age5-en-067.mp3",
    "Which tool helps in the middle of the growing story?": "audio/natural/en/age5-en-068.mp3",
    "Tap the beginning of the plant story.": "audio/natural/en/age5-en-069.mp3",
    "Tap the ending of the plant story.": "audio/natural/en/age5-en-070.mp3",
    "Which group has more apples?": "audio/natural/en/age5-en-071.mp3",
    "Which group has fewer apples than two?": "audio/natural/en/age5-en-072.mp3",
    "Which picture has equal groups?": "audio/natural/en/age5-en-073.mp3",
    "Find the group with four apples.": "audio/natural/en/age5-en-074.mp3",
    "Which group has only one apple?": "audio/natural/en/age5-en-075.mp3",
    "Find two groups with the same number.": "audio/natural/en/age5-en-076.mp3",
    "One plus one makes how many?": "audio/natural/en/age5-en-077.mp3",
    "Two plus one makes how many?": "audio/natural/en/age5-en-078.mp3",
    "Three minus two leaves how many?": "audio/natural/en/age5-en-079.mp3",
    "Three plus two makes how many?": "audio/natural/en/age5-en-080.mp3",
    "Five minus two leaves how many?": "audio/natural/en/age5-en-081.mp3",
    "Five minus three leaves how many?": "audio/natural/en/age5-en-082.mp3",
    "Which flat shape is round?": "audio/natural/en/age5-en-083.mp3",
    "Which flat shape has three sides?": "audio/natural/en/age5-en-084.mp3",
    "Which solid shape has flat square faces?": "audio/natural/en/age5-en-085.mp3",
    "Which solid shape rolls like a ball?": "audio/natural/en/age5-en-086.mp3",
    "Find a two-dimensional triangle.": "audio/natural/en/age5-en-087.mp3",
    "Find a three-dimensional cube.": "audio/natural/en/age5-en-088.mp3",
    "Which child looks happy?": "audio/natural/en/age5-en-089.mp3",
    "Which child looks sad and may need comfort?": "audio/natural/en/age5-en-090.mp3",
    "Which child has a frown and looks angry?": "audio/natural/en/age5-en-091.mp3",
    "Which child looks scared?": "audio/natural/en/age5-en-092.mp3",
    "Find the face with a smile.": "audio/natural/en/age5-en-093.mp3",
    "Find the child who could pause and breathe when angry.": "audio/natural/en/age5-en-094.mp3",
    "Which tool can help the body become calm?": "audio/natural/en/age5-en-095.mp3",
    "Which is a gentle comforting tool?": "audio/natural/en/age5-en-096.mp3",
    "Which choice cares for your body after activity?": "audio/natural/en/age5-en-097.mp3",
    "Which is not a safe calming tool?": "audio/natural/en/age5-en-098.mp3",
    "Find the picture for slow breathing with a feather.": "audio/natural/en/age5-en-099.mp3",
    "What can you do when you are thirsty and upset?": "audio/natural/en/age5-en-100.mp3",
    "Which picture shows sharing?": "audio/natural/en/age5-en-101.mp3",
    "What can you do while a friend is still playing?": "audio/natural/en/age5-en-102.mp3",
    "Which action may hurt a friend's feelings?": "audio/natural/en/age5-en-103.mp3",
    "Which tool can help everyone take fair turns?": "audio/natural/en/age5-en-104.mp3",
    "Find two children using blocks together.": "audio/natural/en/age5-en-105.mp3",
    "Choose a safe way to handle wanting the same toy.": "audio/natural/en/age5-en-106.mp3",
    "What can you do when a puzzle feels hard?": "audio/natural/en/age5-en-107.mp3",
    "What can you do after trying and still feeling stuck?": "audio/natural/en/age5-en-108.mp3",
    "Which choice helps when your body feels tired?": "audio/natural/en/age5-en-109.mp3",
    "Which action does not help us learn?": "audio/natural/en/age5-en-110.mp3",
    "Find the picture that means try a new way.": "audio/natural/en/age5-en-111.mp3",
    "We can return after a short rest. Which picture shows that?": "audio/natural/en/age5-en-112.mp3",
    "What does a plant need to grow?": "audio/natural/en/age5-en-113.mp3",
    "What kind of light do plant leaves need?": "audio/natural/en/age5-en-114.mp3",
    "What do animals need for energy?": "audio/natural/en/age5-en-115.mp3",
    "Which is not a basic need of all living things?": "audio/natural/en/age5-en-116.mp3",
    "What does a thirsty animal need?": "audio/natural/en/age5-en-117.mp3",
    "Find what warms and lights a plant.": "audio/natural/en/age5-en-118.mp3",
    "What should you wear before riding a balance bike?": "audio/natural/en/age5-en-119.mp3",
    "Which picture shows a safe way to cross a road?": "audio/natural/en/age5-en-120.mp3",
    "Which item should only be handled with an adult?": "audio/natural/en/age5-en-121.mp3",
    "Where must fingers never go?": "audio/natural/en/age5-en-122.mp3",
    "Find what protects your head.": "audio/natural/en/age5-en-123.mp3",
    "Who should help when you cross a road?": "audio/natural/en/age5-en-124.mp3",
    "Where should the robot be before the instructions begin?": "audio/natural/en/age5-en-125.mp3",
    "Which picture means move forward one step?": "audio/natural/en/age5-en-126.mp3",
    "Which instruction is needed when the path bends?": "audio/natural/en/age5-en-127.mp3",
    "Where does the robot arrive after all the steps?": "audio/natural/en/age5-en-128.mp3",
    "Find the place where the first step begins.": "audio/natural/en/age5-en-129.mp3",
    "Find the picture that shows the mission is complete.": "audio/natural/en/age5-en-130.mp3",
    "What helps scientists know dinosaurs once lived?": "audio/natural/en/age5-en-131.mp3",
    "Which dinosaur had huge teeth and two short arms?": "audio/natural/en/age5-en-132.mp3",
    "Which dinosaur had three horns and a large frill?": "audio/natural/en/age5-en-133.mp3",
    "Which picture does not match real history?": "audio/natural/en/age5-en-134.mp3",
    "Find the dinosaur clue preserved in rock.": "audio/natural/en/age5-en-135.mp3",
    "Find the plant-eating Triceratops.": "audio/natural/en/age5-en-136.mp3",
    "Which insect has colourful wings?": "audio/natural/en/age5-en-137.mp3",
    "Which insect often carries food with its colony?": "audio/natural/en/age5-en-138.mp3",
    "Which minibeast has eight legs and is not an insect?": "audio/natural/en/age5-en-139.mp3",
    "Which minibeast carries a shell and crawls slowly?": "audio/natural/en/age5-en-140.mp3",
    "Find the tiny ant with six legs.": "audio/natural/en/age5-en-141.mp3",
    "Find the animal that spins a web.": "audio/natural/en/age5-en-142.mp3",
    "Which large ocean animal comes to the surface to breathe?": "audio/natural/en/age5-en-143.mp3",
    "Which animal has eight arms?": "audio/natural/en/age5-en-144.mp3",
    "Which reptile has a shell and flippers?": "audio/natural/en/age5-en-145.mp3",
    "Which picture shows many fish swimming together?": "audio/natural/en/age5-en-146.mp3",
    "Find the whale blowing air at the surface.": "audio/natural/en/age5-en-147.mp3",
    "Find the animal that can hold things with its arms.": "audio/natural/en/age5-en-148.mp3",
    "Which organ keeps pumping blood around the body?": "audio/natural/en/age5-en-149.mp3",
    "Where does air go when we breathe?": "audio/natural/en/age5-en-150.mp3",
    "Which organ helps digest food after we eat?": "audio/natural/en/age5-en-151.mp3",
    "What supports the body and protects organs?": "audio/natural/en/age5-en-152.mp3",
    "Which organ beats faster after running?": "audio/natural/en/age5-en-153.mp3",
    "Which organs fill with air during a deep breath?": "audio/natural/en/age5-en-154.mp3",
    "What weather has a bright sky with very few clouds?": "audio/natural/en/age5-en-155.mp3",
    "Which weather calls for an umbrella?": "audio/natural/en/age5-en-156.mp3",
    "What weather makes leaves swirl through the air?": "audio/natural/en/age5-en-157.mp3",
    "What weather brings lightning and thunder?": "audio/natural/en/age5-en-158.mp3",
    "Find the weather for rain boots and puddles.": "audio/natural/en/age5-en-159.mp3",
    "Find the weather that can lift a kite.": "audio/natural/en/age5-en-160.mp3",
    "In which season do many flowers bloom?": "audio/natural/en/age5-en-161.mp3",
    "Which season is usually the hottest?": "audio/natural/en/age5-en-162.mp3",
    "In which season do many leaves change colour and fall?": "audio/natural/en/age5-en-163.mp3",
    "In which season do some places get snow?": "audio/natural/en/age5-en-164.mp3",
    "Find the new flowers of spring.": "audio/natural/en/age5-en-165.mp3",
    "Find the season for a warm coat.": "audio/natural/en/age5-en-166.mp3",
    "Which star gives Earth light and warmth?": "audio/natural/en/age5-en-167.mp3",
    "Which object often seen at night travels around Earth?": "audio/natural/en/age5-en-168.mp3",
    "Which planet do we live on?": "audio/natural/en/age5-en-169.mp3",
    "Who wears a spacesuit to work in space?": "audio/natural/en/age5-en-170.mp3",
    "Find the blue planet with oceans and land.": "audio/natural/en/age5-en-171.mp3",
    "Find the Moon, which reflects sunlight.": "audio/natural/en/age5-en-172.mp3",
    "Which mountain can release lava and ash?": "audio/natural/en/age5-en-173.mp3",
    "What do we call a sudden shaking of the ground?": "audio/natural/en/age5-en-174.mp3",
    "Which action helps protect you during an earthquake?": "audio/natural/en/age5-en-175.mp3",
    "What is the very hot melted rock from a volcano called?": "audio/natural/en/age5-en-176.mp3",
    "Find drop, cover, and hold on.": "audio/natural/en/age5-en-177.mp3",
    "Find the volcano that is erupting.": "audio/natural/en/age5-en-178.mp3",
    "Which item does your body need every day?": "audio/natural/en/age5-en-179.mp3",
    "Which provides a safe place to live?": "audio/natural/en/age5-en-180.mp3",
    "Which is fun but not needed for survival?": "audio/natural/en/age5-en-181.mp3",
    "Which is a treat we may want sometimes?": "audio/natural/en/age5-en-182.mp3",
    "Choose what you need when you are thirsty.": "audio/natural/en/age5-en-183.mp3",
    "Find something that is a want, not a need.": "audio/natural/en/age5-en-184.mp3",
    "What can be the first step when buying something?": "audio/natural/en/age5-en-185.mp3",
    "What do we do after choosing an item?": "audio/natural/en/age5-en-186.mp3",
    "Which paper records what was bought?": "audio/natural/en/age5-en-187.mp3",
    "Which action is not okay?": "audio/natural/en/age5-en-188.mp3",
    "Find the picture of giving money to the cashier.": "audio/natural/en/age5-en-189.mp3",
    "Find the small paper you may receive after buying.": "audio/natural/en/age5-en-190.mp3",
    "Which container can hold money you are saving?": "audio/natural/en/age5-en-191.mp3",
    "What can you add a little at a time?": "audio/natural/en/age5-en-192.mp3",
    "Which picture shows a savings goal?": "audio/natural/en/age5-en-193.mp3",
    "Which choice makes your savings smaller?": "audio/natural/en/age5-en-194.mp3",
    "Find the container where coins can slowly grow.": "audio/natural/en/age5-en-195.mp3",
    "When saving, choose a goal. Which picture shows one?": "audio/natural/en/age5-en-196.mp3",
    "Which robot can repeatedly move things in a factory?": "audio/natural/en/age5-en-197.mp3",
    "Which robot moves across a floor to clean?": "audio/natural/en/age5-en-198.mp3",
    "Which robot can explore a distant planet?": "audio/natural/en/age5-en-199.mp3",
    "Which one is not a robot?": "audio/natural/en/age5-en-200.mp3",
    "Find the wheeled robot that explores rocks.": "audio/natural/en/age5-en-201.mp3",
    "Find the machine that helps clean at home.": "audio/natural/en/age5-en-202.mp3",
    "Which device receives information and runs apps?": "audio/natural/en/age5-en-203.mp3",
    "Which device can hear a spoken request and answer?": "audio/natural/en/age5-en-204.mp3",
    "Which device simply turns on with a switch and may not be smart?": "audio/natural/en/age5-en-205.mp3",
    "Which item is not an electronic device at all?": "audio/natural/en/age5-en-206.mp3",
    "Find the phone that may connect to the internet.": "audio/natural/en/age5-en-207.mp3",
    "Find the tool used only to stir food.": "audio/natural/en/age5-en-208.mp3",
    "What is the first step for a voice assistant?": "audio/natural/en/age5-en-209.mp3",
    "What does the computer look for after receiving sound?": "audio/natural/en/age5-en-210.mp3",
    "What can the device do after finding a likely meaning?": "audio/natural/en/age5-en-211.mp3",
    "What is important when using a voice assistant?": "audio/natural/en/age5-en-212.mp3",
    "Find the first step that turns sound into computer clues.": "audio/natural/en/age5-en-213.mp3",
    "Find the picture where the device speaks the result.": "audio/natural/en/age5-en-214.mp3",
    "Which ancient building has a wide base and pointed top?": "audio/natural/en/age5-en-215.mp3",
    "What was mainly stacked to build pyramids?": "audio/natural/en/age5-en-216.mp3",
    "Which river flowed through ancient Egypt and helped move supplies?": "audio/natural/en/age5-en-217.mp3",
    "Which modern machine did ancient Egyptian workers not have?": "audio/natural/en/age5-en-218.mp3",
    "Find the great stone tomb in the story.": "audio/natural/en/age5-en-219.mp3",
    "Find the river where boats could carry stone.": "audio/natural/en/age5-en-220.mp3",
    "Which high place lets people look far away?": "audio/natural/en/age5-en-221.mp3",
    "Which entrance could be raised to protect a castle?": "audio/natural/en/age5-en-222.mp3",
    "Where might people eat and meet together?": "audio/natural/en/age5-en-223.mp3",
    "What would an old castle usually not have?": "audio/natural/en/age5-en-224.mp3",
    "Find the tall castle tower.": "audio/natural/en/age5-en-225.mp3",
    "Find the gate people used to enter the castle.": "audio/natural/en/age5-en-226.mp3",
    "What did a knight wear to protect the body?": "audio/natural/en/age5-en-227.mp3",
    "What could a knight hold to block a blow?": "audio/natural/en/age5-en-228.mp3",
    "Which animal did knights often ride?": "audio/natural/en/age5-en-229.mp3",
    "Which item does not belong in a knight story?": "audio/natural/en/age5-en-230.mp3",
    "Find the protective clothing made of metal.": "audio/natural/en/age5-en-231.mp3",
    "Find the protective board with an emblem.": "audio/natural/en/age5-en-232.mp3",
    "Which goddess is often shown with a wise owl?": "audio/natural/en/age5-en-233.mp3",
    "Which sea god carries a trident?": "audio/natural/en/age5-en-234.mp3",
    "Which mythical horse has wings?": "audio/natural/en/age5-en-235.mp3",
    "Which character does not belong in an ancient Greek myth?": "audio/natural/en/age5-en-236.mp3",
    "Find the flying horse in the story.": "audio/natural/en/age5-en-237.mp3",
    "Find the mythical figure connected with the sea.": "audio/natural/en/age5-en-238.mp3",
    "What do we use to observe colour and shape?": "audio/natural/en/age5-en-239.mp3",
    "Which tool makes tiny details look bigger?": "audio/natural/en/age5-en-240.mp3",
    "How can we observe whether bark is rough?": "audio/natural/en/age5-en-241.mp3",
    "Which is not careful observation?": "audio/natural/en/age5-en-242.mp3",
    "Find the tool for seeing leaf-vein details.": "audio/natural/en/age5-en-243.mp3",
    "Find a way to collect clues with touch.": "audio/natural/en/age5-en-244.mp3",
    "Which picture could begin a why question about melting?": "audio/natural/en/age5-en-245.mp3",
    "Which picture asks what happens with different light?": "audio/natural/en/age5-en-246.mp3",
    "What can you do when you do not understand?": "audio/natural/en/age5-en-247.mp3",
    "What should we not do immediately when a science question begins?": "audio/natural/en/age5-en-248.mp3",
    "Find a question that compares two conditions.": "audio/natural/en/age5-en-249.mp3",
    "Find the child bravely asking a question.": "audio/natural/en/age5-en-250.mp3",
    "What can we prepare first for a fair comparison?": "audio/natural/en/age5-en-251.mp3",
    "What can be the next step in a float-or-sink test?": "audio/natural/en/age5-en-252.mp3",
    "What should we do carefully after the object enters the water?": "audio/natural/en/age5-en-253.mp3",
    "What must we never do with experiment materials?": "audio/natural/en/age5-en-254.mp3",
    "Find the picture where results are observed.": "audio/natural/en/age5-en-255.mp3",
    "Find the step where an object is gently placed in water.": "audio/natural/en/age5-en-256.mp3",
    "What can we draw before an experiment begins?": "audio/natural/en/age5-en-257.mp3",
    "Which record should be added after the seed sprouts?": "audio/natural/en/age5-en-258.mp3",
    "What can record seeing five objects?": "audio/natural/en/age5-en-259.mp3",
    "Which action would make the observation record disappear?": "audio/natural/en/age5-en-260.mp3",
    "Find the drawing that shows the later change.": "audio/natural/en/age5-en-261.mp3",
    "Find a way to record quantity without many words.": "audio/natural/en/age5-en-262.mp3",
    "Which step can begin a science mission?": "audio/natural/en/age5-en-263.mp3",
    "What can we do after observing?": "audio/natural/en/age5-en-264.mp3",
    "What can we safely do to look for an answer?": "audio/natural/en/age5-en-265.mp3",
    "How can we save the result after a test?": "audio/natural/en/age5-en-266.mp3",
    "Find the step that collects clues with your eyes.": "audio/natural/en/age5-en-267.mp3",
    "Find the final step that draws what happened.": "audio/natural/en/age5-en-268.mp3",
    "Find three pairs of ocean animals.": "audio/natural/en/age5-en-269.mp3",
    "Turn over two cards and remember where they are.": "audio/natural/en/age5-en-270.mp3",
    "Find three pairs of dinosaur friends.": "audio/natural/en/age5-en-271.mp3",
    "Find four matching pairs.": "audio/natural/en/age5-en-272.mp3",
    "Find four pairs from the sky.": "audio/natural/en/age5-en-273.mp3",
    "Find five pairs of space friends.": "audio/natural/en/age5-en-274.mp3",
    "Complete the six-pair memory challenge.": "audio/natural/en/age5-en-275.mp3",
    "Remember the apple, banana, and strawberry.": "audio/natural/en/age5-en-276.mp3",
    "Look slowly at every picture.": "audio/natural/en/age5-en-277.mp3",
    "Which one is missing?": "audio/natural/en/age5-en-278.mp3",
    "Look at the pictures that remain, then remember who else you saw.": "audio/natural/en/age5-en-279.mp3",
    "Remember the Tyrannosaurus, Triceratops, and dinosaur egg.": "audio/natural/en/age5-en-280.mp3",
    "Remember the four minibeasts.": "audio/natural/en/age5-en-281.mp3",
    "Remember the Sun, Moon, Earth, and rocket.": "audio/natural/en/age5-en-282.mp3",
    "Remember the eyes, ears, nose, tongue, and hands.": "audio/natural/en/age5-en-283.mp3",
    "Remember these five mixed picture cards.": "audio/natural/en/age5-en-284.mp3",
    "Little ears ready. Listen carefully. Which picture matches the sound?": "audio/natural/en/age5-en-285.mp3",
    "Play it again and find where the sound comes from.": "audio/natural/en/age5-en-286.mp3",
    "First the Moon, then the rocket. Remember them.": "audio/natural/en/age5-en-287.mp3",
    "Watch each picture light up.": "audio/natural/en/age5-en-288.mp3",
    "Your turn. Tap the pictures in the same order.": "audio/natural/en/age5-en-289.mp3",
    "Think about which picture lit up first.": "audio/natural/en/age5-en-290.mp3",
    "First the butterfly, then the flower. Remember them.": "audio/natural/en/age5-en-291.mp3",
    "Dinosaur egg, Triceratops, fossil. Remember the order.": "audio/natural/en/age5-en-292.mp3",
    "Microphone, computer, smart speaker. Remember the voice-assistant order.": "audio/natural/en/age5-en-293.mp3",
    "Observe, ask, experiment, draw. Remember the science mission.": "audio/natural/en/age5-en-294.mp3",
    "Sun, Earth, Moon, astronaut. Remember the final space order.": "audio/natural/en/age5-en-295.mp3",
    "star": "audio/natural/en/age5-en-296.mp3",
    "dog": "audio/natural/en/age5-en-297.mp3",
    "book": "audio/natural/en/age5-en-298.mp3",
    "hat": "audio/natural/en/age5-en-299.mp3",
    "fish": "audio/natural/en/age5-en-300.mp3",
    "cup": "audio/natural/en/age5-en-301.mp3",
    "frog": "audio/natural/en/age5-en-302.mp3",
    "cat": "audio/natural/en/age5-en-303.mp3",
    "moon": "audio/natural/en/age5-en-304.mp3",
    "dish": "audio/natural/en/age5-en-305.mp3",
    "car": "audio/natural/en/age5-en-306.mp3",
    "spoon": "audio/natural/en/age5-en-307.mp3",
    "sun": "audio/natural/en/age5-en-308.mp3",
    "ears": "audio/natural/en/age5-en-309.mp3",
    "eyes": "audio/natural/en/age5-en-310.mp3",
    "nose": "audio/natural/en/age5-en-311.mp3",
    "tongue": "audio/natural/en/age5-en-312.mp3",
    "skin and hands": "audio/natural/en/age5-en-313.mp3",
    "hearing": "audio/natural/en/age5-en-314.mp3",
    "smell": "audio/natural/en/age5-en-315.mp3",
    "taste": "audio/natural/en/age5-en-316.mp3",
    "phone": "audio/natural/en/age5-en-317.mp3",
    "paper book": "audio/natural/en/age5-en-318.mp3",
    "robot": "audio/natural/en/age5-en-319.mp3",
    "adult": "audio/natural/en/age5-en-320.mp3",
    "smart speaker": "audio/natural/en/age5-en-321.mp3",
    "bowl": "audio/natural/en/age5-en-322.mp3",
    "towel": "audio/natural/en/age5-en-323.mp3",
    "automatic door": "audio/natural/en/age5-en-324.mp3",
    "banana": "audio/natural/en/age5-en-325.mp3",
    "check with an adult": "audio/natural/en/age5-en-326.mp3",
    "always trust the machine": "audio/natural/en/age5-en-327.mp3",
    "ignore it": "audio/natural/en/age5-en-328.mp3",
    "AI robot": "audio/natural/en/age5-en-329.mp3",
    "child": "audio/natural/en/age5-en-330.mp3",
    "map": "audio/natural/en/age5-en-331.mp3",
    "girl": "audio/natural/en/age5-en-332.mp3",
    "forest": "audio/natural/en/age5-en-333.mp3",
    "picnic": "audio/natural/en/age5-en-334.mp3",
    "dragon": "audio/natural/en/age5-en-335.mp3",
    "seed": "audio/natural/en/age5-en-336.mp3",
    "sprout": "audio/natural/en/age5-en-337.mp3",
    "flower": "audio/natural/en/age5-en-338.mp3",
    "watering can": "audio/natural/en/age5-en-339.mp3",
    "two apples": "audio/natural/en/age5-en-340.mp3",
    "four apples": "audio/natural/en/age5-en-341.mp3",
    "equal groups": "audio/natural/en/age5-en-342.mp3",
    "one apple": "audio/natural/en/age5-en-343.mp3",
    "one star": "audio/natural/en/age5-en-344.mp3",
    "two stars": "audio/natural/en/age5-en-345.mp3",
    "three stars": "audio/natural/en/age5-en-346.mp3",
    "five stars": "audio/natural/en/age5-en-347.mp3",
    "circle": "audio/natural/en/age5-en-348.mp3",
    "triangle": "audio/natural/en/age5-en-349.mp3",
    "cube": "audio/natural/en/age5-en-350.mp3",
    "sphere": "audio/natural/en/age5-en-351.mp3",
    "happy child": "audio/natural/en/age5-en-352.mp3",
    "sad child": "audio/natural/en/age5-en-353.mp3",
    "angry child": "audio/natural/en/age5-en-354.mp3",
    "scared child": "audio/natural/en/age5-en-355.mp3",
    "slow breathing with a feather": "audio/natural/en/age5-en-356.mp3",
    "hug a soft toy": "audio/natural/en/age5-en-357.mp3",
    "drink water": "audio/natural/en/age5-en-358.mp3",
    "yelling": "audio/natural/en/age5-en-359.mp3",
    "children sharing blocks": "audio/natural/en/age5-en-360.mp3",
    "child waiting for a turn": "audio/natural/en/age5-en-361.mp3",
    "grabbing a toy": "audio/natural/en/age5-en-362.mp3",
    "turn-taking timer": "audio/natural/en/age5-en-363.mp3",
    "child trying a puzzle again": "audio/natural/en/age5-en-364.mp3",
    "asking an adult for help": "audio/natural/en/age5-en-365.mp3",
    "taking a short break": "audio/natural/en/age5-en-366.mp3",
    "throwing the puzzle away": "audio/natural/en/age5-en-367.mp3",
    "water": "audio/natural/en/age5-en-368.mp3",
    "sunlight": "audio/natural/en/age5-en-369.mp3",
    "food": "audio/natural/en/age5-en-370.mp3",
    "toy car": "audio/natural/en/age5-en-371.mp3",
    "child wearing a helmet": "audio/natural/en/age5-en-372.mp3",
    "crossing with an adult": "audio/natural/en/age5-en-373.mp3",
    "medicine bottle": "audio/natural/en/age5-en-374.mp3",
    "electric socket": "audio/natural/en/age5-en-375.mp3",
    "robot at the start": "audio/natural/en/age5-en-376.mp3",
    "robot moving forward": "audio/natural/en/age5-en-377.mp3",
    "robot turning": "audio/natural/en/age5-en-378.mp3",
    "robot reaching a star": "audio/natural/en/age5-en-379.mp3",
    "dinosaur fossil": "audio/natural/en/age5-en-380.mp3",
    "Tyrannosaurus": "audio/natural/en/age5-en-381.mp3",
    "Triceratops": "audio/natural/en/age5-en-382.mp3",
    "modern human beside dinosaur": "audio/natural/en/age5-en-383.mp3",
    "butterfly": "audio/natural/en/age5-en-384.mp3",
    "ant": "audio/natural/en/age5-en-385.mp3",
    "spider": "audio/natural/en/age5-en-386.mp3",
    "snail": "audio/natural/en/age5-en-387.mp3",
    "whale": "audio/natural/en/age5-en-388.mp3",
    "octopus": "audio/natural/en/age5-en-389.mp3",
    "sea turtle": "audio/natural/en/age5-en-390.mp3",
    "school of fish": "audio/natural/en/age5-en-391.mp3",
    "heart": "audio/natural/en/age5-en-392.mp3",
    "lungs": "audio/natural/en/age5-en-393.mp3",
    "stomach": "audio/natural/en/age5-en-394.mp3",
    "bones": "audio/natural/en/age5-en-395.mp3",
    "sunny weather": "audio/natural/en/age5-en-396.mp3",
    "rainy weather": "audio/natural/en/age5-en-397.mp3",
    "windy weather": "audio/natural/en/age5-en-398.mp3",
    "thunderstorm": "audio/natural/en/age5-en-399.mp3",
    "spring blossoms": "audio/natural/en/age5-en-400.mp3",
    "summer sunshine": "audio/natural/en/age5-en-401.mp3",
    "autumn leaves": "audio/natural/en/age5-en-402.mp3",
    "winter snow": "audio/natural/en/age5-en-403.mp3",
    "Sun": "audio/natural/en/age5-en-404.mp3",
    "Moon": "audio/natural/en/age5-en-405.mp3",
    "Earth": "audio/natural/en/age5-en-406.mp3",
    "astronaut": "audio/natural/en/age5-en-407.mp3",
    "erupting volcano": "audio/natural/en/age5-en-408.mp3",
    "shaking ground": "audio/natural/en/age5-en-409.mp3",
    "drop cover and hold on": "audio/natural/en/age5-en-410.mp3",
    "lava": "audio/natural/en/age5-en-411.mp3",
    "drinking water": "audio/natural/en/age5-en-412.mp3",
    "home": "audio/natural/en/age5-en-413.mp3",
    "new toy": "audio/natural/en/age5-en-414.mp3",
    "candy": "audio/natural/en/age5-en-415.mp3",
    "choosing an apple": "audio/natural/en/age5-en-416.mp3",
    "paying money": "audio/natural/en/age5-en-417.mp3",
    "receipt": "audio/natural/en/age5-en-418.mp3",
    "taking it without paying": "audio/natural/en/age5-en-419.mp3",
    "saving jar": "audio/natural/en/age5-en-420.mp3",
    "one coin": "audio/natural/en/age5-en-421.mp3",
    "bicycle goal": "audio/natural/en/age5-en-422.mp3",
    "buying candy right away": "audio/natural/en/age5-en-423.mp3",
    "factory robot arm": "audio/natural/en/age5-en-424.mp3",
    "robot vacuum": "audio/natural/en/age5-en-425.mp3",
    "space rover": "audio/natural/en/age5-en-426.mp3",
    "human friend": "audio/natural/en/age5-en-427.mp3",
    "smartphone": "audio/natural/en/age5-en-428.mp3",
    "ordinary lamp": "audio/natural/en/age5-en-429.mp3",
    "wooden spoon": "audio/natural/en/age5-en-430.mp3",
    "microphone receives sound": "audio/natural/en/age5-en-431.mp3",
    "computer matches speech patterns": "audio/natural/en/age5-en-432.mp3",
    "speaker gives an answer": "audio/natural/en/age5-en-433.mp3",
    "keeping private information safe": "audio/natural/en/age5-en-434.mp3",
    "Egyptian pyramid": "audio/natural/en/age5-en-435.mp3",
    "large stone blocks": "audio/natural/en/age5-en-436.mp3",
    "Nile River and boat": "audio/natural/en/age5-en-437.mp3",
    "modern crane": "audio/natural/en/age5-en-438.mp3",
    "castle tower": "audio/natural/en/age5-en-439.mp3",
    "drawbridge and gate": "audio/natural/en/age5-en-440.mp3",
    "great hall": "audio/natural/en/age5-en-441.mp3",
    "modern garage": "audio/natural/en/age5-en-442.mp3",
    "knight's armour": "audio/natural/en/age5-en-443.mp3",
    "shield": "audio/natural/en/age5-en-444.mp3",
    "horse": "audio/natural/en/age5-en-445.mp3",
    "spacesuit": "audio/natural/en/age5-en-446.mp3",
    "Athena and owl": "audio/natural/en/age5-en-447.mp3",
    "Poseidon and trident": "audio/natural/en/age5-en-448.mp3",
    "Pegasus": "audio/natural/en/age5-en-449.mp3",
    "modern robot": "audio/natural/en/age5-en-450.mp3",
    "child looking at a leaf": "audio/natural/en/age5-en-451.mp3",
    "magnifying glass": "audio/natural/en/age5-en-452.mp3",
    "hand touching bark": "audio/natural/en/age5-en-453.mp3",
    "guessing with eyes closed": "audio/natural/en/age5-en-454.mp3",
    "child wondering about melting ice": "audio/natural/en/age5-en-455.mp3",
    "plants in different light": "audio/natural/en/age5-en-456.mp3",
    "raising a hand to ask": "audio/natural/en/age5-en-457.mp3",
    "announcing an answer without checking": "audio/natural/en/age5-en-458.mp3",
    "two cups of water": "audio/natural/en/age5-en-459.mp3",
    "placing an object in water": "audio/natural/en/age5-en-460.mp3",
    "observing float or sink": "audio/natural/en/age5-en-461.mp3",
    "tasting experiment materials": "audio/natural/en/age5-en-462.mp3",
    "seed drawing before experiment": "audio/natural/en/age5-en-463.mp3",
    "sprout drawing after experiment": "audio/natural/en/age5-en-464.mp3",
    "counting marks": "audio/natural/en/age5-en-465.mp3",
    "erasing every result": "audio/natural/en/age5-en-466.mp3",
    "observe a leaf": "audio/natural/en/age5-en-467.mp3",
    "ask a question": "audio/natural/en/age5-en-468.mp3",
    "do a simple test": "audio/natural/en/age5-en-469.mp3",
    "draw the result": "audio/natural/en/age5-en-470.mp3",
    "dinosaur egg": "audio/natural/en/age5-en-471.mp3",
    "bee": "audio/natural/en/age5-en-472.mp3",
    "rain cloud": "audio/natural/en/age5-en-473.mp3",
    "wind": "audio/natural/en/age5-en-474.mp3",
    "rocket": "audio/natural/en/age5-en-475.mp3",
    "apple": "audio/natural/en/age5-en-476.mp3",
    "strawberry": "audio/natural/en/age5-en-477.mp3",
    "hands": "audio/natural/en/age5-en-478.mp3",
    "ocean": "audio/natural/en/age5-en-479.mp3",
    "castle": "audio/natural/en/age5-en-480.mp3",
    "ship": "audio/natural/en/age5-en-481.mp3",
    "bicycle": "audio/natural/en/age5-en-482.mp3",
    "fossil": "audio/natural/en/age5-en-483.mp3",
    "microphone": "audio/natural/en/age5-en-484.mp3",
    "computer": "audio/natural/en/age5-en-485.mp3",
    "do an experiment": "audio/natural/en/age5-en-486.mp3"
  }
};
